### PR TITLE
Eduardo Padilla - DS17

### PR DESCRIPTION
**Pull request by eduardopadilla3**

### CODE REVIEW

**Comment by mljarman** [comment]
Good first assignment! The code is cleaned and organized well in the cells. A couple of little things, the categorical variables weren't represented for their descriptive statistics. `df.describe(exclude='number')` is the syntax and in the second dataset it's just df.describe, need to add () when calling that. 

Maybe try some stretch goals! You got it!

**Comment by mljarman** [comment]
Good job replicating the class code, but there were 3 additional objectives needed to complete the assignment: 

- Convert the term column from string to integer.
- Make a column named loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make last_pymnt_d_month and last_pymnt_d_year columns.

**Comment by eduardopadilla3** [comment]
I submitted another module that was complete

**Comment by mljarman** [comment]
Good assignment Eduardo!

Your value counts are correct for the top 10 products. I wanted to mention, although it was correct and it worked, but, your long conditions for the top 10 could be more concise. You could use value_counts, I think you mentioned you tried doing that so we can go over that in our 1:1.

Also, for the tidy back into table 2, the parameters are out of order. Think about for pivot tables, the parameters are where you want the data to go. So what should be the index? The column names? And the values? Quick fix.

**Pull request closed without merging**
