### PR TITLE
Thomas - John - TL - Serina - DS17

### PR DESCRIPTION
**Pull request by John-G-Thomas**

### CODE REVIEW

**Comment by serinamarie** [comment]
Great use of a histogram and density plot to explore the iris dataset. However, as you probably noticed, a scatterplot is not the best way to glean insights from the iris species types. Good use of seaborn's pairplot to explore all relationships in the dataset. This can often be a good way to start and can also be explored with pandas profiling.

**Comment by serinamarie** [comment]
Your last_pymnt_d_month and year columns should be integers. Great job on your func function. Perhaps name your functions something more descriptive than func next time, though. Nice term_to_int function. However, this looks just like Dondre's function. Make sure you still are doing your own work in terms of naming your variables, etc!

Overall great job.

**Comment by serinamarie** [comment]
I would also recommend renaming your pull request to 

**Thomas - John - TL - Serina - DS1**7 (deleting 'Robert') so as not to confuse Robert :)

**Comment by John-G-Thomas** [comment]
okay, will do might take me a day doing the assignment in mcdonalds parking
lot atm because my internet provider is having a unexpected outage

**Comment by serinamarie** [comment]
I know this assignment isn't quite done, but for part 3, you just need to widen the flight data.

**Comment by John-G-Thomas** [comment]
Okay, Thank you

**Comment by serinamarie** [comment]
So, basically, placing it in a dataframe.

**Comment by John-G-Thomas** [comment]
okay, thanks again

**Comment by John-G-Thomas** [comment]
Alright I finished the assignment and all caught up thanks again for the
lenience

**Pull request closed without merging**
